# Generated by Django 5.2.17 on 2026-08-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='superintendent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='government.superintendentprofile'),
        ),
    ]
