# Generated by Django 5.2.17 on 2026-08-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_area_latitude_alter_area_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='radius',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
