# Generated by Django 5.2.17 on 2026-08-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_area_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='radius',
            field=models.PositiveIntegerField(default=2000, editable=False),
        ),
    ]
