# Generated by Django 5.2.17 on 2026-08-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_handed_over',
        ),
        migrations.AddField(
            model_name='post',
            name='action',
            field=models.CharField(blank=True, choices=[('self_resolve', 'Self Resolve'), ('handover', 'Hand Over to Authority')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DuplicatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_posts', to='posts.post')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_info', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('media_type', models.CharField(choices=[('original', 'Original'), ('cleanup', 'Cleanup')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
        ),
    ]
