# Generated by Django 5.2.17 on 2026-08-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_area_radius'),
        ('posts', '0003_alter_post_latitude_alter_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='areas.area'),
        ),
    ]
