# Generated by Django 5.2.17 on 2026-08-15 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='credit_points',
            field=models.DecimalField(decimal_places=1, default=9.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
