# Generated by Django 5.2.17 on 2026-08-15 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_credit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='credit_points',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
