# Generated by Django 5.2.17 on 2026-08-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_credit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waste_volume',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
    ]
