# Generated by Django 5.2.17 on 2026-08-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_credit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='waste_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
