# Generated by Django 5.2.17 on 2026-08-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_waste_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='waste_volume',
        ),
    ]
