# Generated by Django 5.2.17 on 2026-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_ai_confidence_post_waste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waste_volume',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True),
        ),
    ]
