# Generated by Django 5.2.17 on 2026-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_waste_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='volume_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
