# Generated by Django 5.2.17 on 2026-08-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_volume_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='volume_percent',
        ),
    ]
