<<<<<<< HEAD
# Generated by Django 5.2.17 on 2026-08-17 15:26
=======
# Generated by Django 5.2.17 on 2026-08-18 12:12
>>>>>>> 2464a02207ecafa817113b83de98b093799e7eab

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_volume_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='volume_percent',
        ),
    ]
