# Generated by Django 5.2.17 on 2026-08-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_total_credit_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_credit_points',
        ),
    ]
