# Generated by Django 5.2.17 on 2026-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_total_credit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('superintendent', 'Superintendent'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
